task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views


urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('users/', include('users.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
    path('labels/', include('labels.urls')),
    path('admin/', admin.site.urls)
]

tasks/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.TaskListView.as_view(), name='task_list'),
    path('<int:pk>', views.TaskView.as_view(), name='task_view'),
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(),
         name='task_update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(),
         name='task_delete')
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.UsersView.as_view(), name='users'),
    path('create/', views.SignUpView.as_view(), name='signup'),
    path('<int:pk>/update/', views.CustomUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete')
]

labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):

    name = models.CharField(max_length=100, verbose_name=_('Name'))
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import User


def get_full_name(self):
    return self.get_full_name()


User.add_to_class("__str__", get_full_name)

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username']


class CustomUserChangeForm(CustomUserCreationForm):

    def clean_username(self):
        return self.cleaned_data.get("username")

users/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.db.models import ProtectedError
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import (ListView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
from . import forms


class UsersView(ListView):

    model = User
    template_name = 'users/user_list.html'


class UserPermissionMixin(UserPassesTestMixin):

    def test_func(self):
        return self.request.user.id == self.kwargs['pk']

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.error(self.request,
                           _("You can't edit other user's profile."))
            return redirect(reverse_lazy('users'))
        else:
            messages.warning(self.request,
                             _("You are not authorized! Please log in."))
            return redirect(reverse_lazy('login'))


class SignUpView(SuccessMessageMixin, CreateView):

    form_class = forms.CustomUserCreationForm
    template_name = 'users/user_create.html'
    success_url = reverse_lazy('login')
    success_message = _('User created successfully')


class CustomUpdateView(UserPermissionMixin,
                       SuccessMessageMixin,
                       UpdateView):

    model = User
    form_class = forms.CustomUserChangeForm
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users')
    success_message = _('User updated successfully')


class DeleteView(UserPermissionMixin,
                 SuccessMessageMixin,
                 DeleteView):

    model = User
    template_name = 'users/user_delete.html'
    success_url = reverse_lazy('users')
    success_message = _('User deleted successfully')

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        try:
            obj.delete()
            messages.success(self.request, self.success_message)
        except ProtectedError:
            messages.error(self.request, _("User can't be deleted as long as they're involved in tasks")) # noqa
        return redirect(self.success_url)

templates/base.html
<!doctype html>
<html lang="en">
{% load i18n %}
{% load django_bootstrap5 %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AF Task Manager</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body class="d-flex flex-column min-vh-100 bg-light">

    {% block nav %}
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">{% trans 'Task Manager' %}</a>

            <div class="collapse navbar-collapse">

                <ul class="navbar-nav me-auto">

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'users' %}">{% trans 'Users' %}</a>
                    </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'st_list' %}">{% trans 'Statuses' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'label_list' %}">{% trans 'Labels' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'task_list' %}">{% trans 'Tasks' %}</a>
                    </li>

                </ul>
                <ul class="navbar-nav ms-auto">
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <input class="btn nav-link" type="submit" value="{% trans 'Log Out' %}">
                    </form>
                </ul>

                {% else %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">{% trans 'Log In' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">{% trans 'Sign Up' %}</a>
                    </li>
                </ul>
                {% endif %}

            </div>
        </div>
    </nav>
    {% endblock nav %}

    <div class="container wrapper flex-grow-1">
        {% bootstrap_messages %}

        {% block content %}
        {% endblock content %}
    </div>

</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="card my-4">
    <div class="card-body p-5 bg-light">
        <div class="display-5">
            <p>{% trans 'HEY' %} {{ user.username }}</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/users.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container-lg mt-3">
    <h1>{% trans 'Users' %}</h1>
    <table class="table table-striped table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">{% trans 'Username' %}</th>
                <th scope="col">{% trans 'Full Name' %}</th>
                <th scope="col">{% trans 'Joined at' %}</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="table-light align-middle">
            {% for user in user_list %}
            <tr>
                <th scope="row">{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.get_full_name }}</td>
                <td>{{ user.date_joined }}</td>
                <td class="d-grid">
                    <a href="{% url 'update' user.id %}" class="link-success">{% trans 'Update' %}</a>
                    <a href="{% url 'delete' user.id %}" class="link-dark">{% trans 'Delete' %}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}